repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: .venv/bin/black
        language: system
        types: [python]
        require_serial: true
      - id: ruff
        name: ruff check
        entry: .venv/bin/ruff check --fix
        language: system
        types: [python]
        require_serial: true
        pass_filenames: true
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: package-lock.json